# Generated by Django 5.2.6 on 2025-10-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
