# Generated by Django 5.2.6 on 2025-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_system', '0002_ticket_attendee_name_ticket_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='event_images/', width_field=100),
        ),
    ]
