# Generated by Django 5.2.6 on 2025-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_system', '0005_alter_event_image_height_alter_event_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=500, null=True),
        ),
    ]
