# Generated by Django 5.2.6 on 2025-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_system', '0006_alter_event_image_height_alter_event_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/.jpg', height_field='image_height', upload_to='event_images/', width_field='image_width'),
        ),
    ]
