# Generated by Django 5.2.6 on 2025-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_system', '0007_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image_height',
            new_name='background_image_height',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image_width',
            new_name='background_image_width',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='background_image',
            field=models.ImageField(default='event_images/.jpg', height_field='background_image_height', upload_to='', width_field='background_image_width'),
        ),
    ]
