# Generated by Django 5.2.6 on 2025-10-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_system', '0008_rename_image_height_event_background_image_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='background_image_height',
        ),
        migrations.RemoveField(
            model_name='event',
            name='background_image_width',
        ),
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_backgrounds/'),
        ),
    ]
